config/routes.rb
Rails.application.routes.draw do
  root to: "catalog#index"
  # we define the root route in initializers/high_voltage.rb
  # root to: "catalog#index"

  mount Blacklight::Engine => '/'

  devise_for :users

  get '/solr_documents/:id/feedback' => 'catalog#feedback', as: 'feedback_solr_document'


  concern :searchable, Blacklight::Routes::Searchable.new
  concern :exportable, Blacklight::Routes::Exportable.new

  resource :catalog, only: [:index], controller: 'catalog' do
    concerns :searchable
  end

  resources :solr_documents, only: [:show], controller: 'catalog' do
    concerns :exportable
  end

  resources :bookmarks do
    concerns :exportable

    collection do
      delete 'clear'
    end
  end


  # OLD ADL routes
  get '/catalog/:id/facsimile' => 'catalog#facsimile', as: 'facsimile_catalog'
  get 'oai' => 'catalog#oai'
  get '/authors' => 'catalog#authors'
  get '/periods' => 'catalog#periods'
  get '/allworks/:authorid' => 'catalog#allworks'
end

app/controllers/catalog_controller.rb
# -*- encoding : utf-8 -*-
class CatalogController < ApplicationController

  include Blacklight::Catalog

  configure_blacklight do |config|
    ## Default parameters to send to solr for all search-like requests. See also SearchBuilder#processed_parameters
    config.default_solr_params = {
      :qt => 'search',
      :rows => 10,
      :fq => ['application_ssim:ADL'],
      :hl => 'true',
      :'hl.snippets' => '3',
      :'hl.simple.pre' => '<em class="highlight" >',
      :'hl.simple.post' => '</em>'
    }
    
    # solr path which will be added to solr base url before the other solr params.
    #config.solr_path = 'select' 
    
    # items to show per page, each number in the array represent another option to choose from.
    #config.per_page = [10,20,50,100]

    ## Default parameters to send on single-document requests to Solr. These settings are the Blackligt defaults (see SearchHelper#solr_doc_params) or
    ## parameters included in the blacklight-jetty document requestHandler.
    #
    #config.default_document_solr_params = {
    #  :qt => 'document',
    #  ## These are hard-coded in the blacklight 'document' requestHandler
    #  # :fl => '*',
    #  # :rows => 1index_field
    #  # :q => '{!raw f=id v=$id}'
    #}

    # solr field configuration for search results/index views
    config.index.title_field = 'work_title_tesim'
    config.index.display_type_field = 'cat_ssi'

    config.index.document_presenter_class = AdlIndexPresenter

    # solr field configuration for document/show views
    #config.show.title_field = 'title_display'
    #config.show.display_type_field = 'format'

    # solr fields that will be treated as facets by the blacklight application
    #   The ordering of the field names is the order of the display
    #
    # Setting a limit will trigger blacklight's 'more' facet values link.
    # * If left unset, then all facet values returned by solr will be displayed.
    # * If set to an integer, then "f.somefield.facet.limit" will be added to
    # solr request, with actual solr request being +1 your configured limit --
    # you configure the number of items you actually want _displayed_ in a page.    
    # * If set to 'true', then no additional parameters will be sent to solr,
    # but any 'sniffed' request limit parameters will be used for paging, with
    # paging at requested limit -1. Can sniff from facet.limit or 
    # f.specific_field.facet.limit solr request params. This 'true' config
    # can be used if you set limits in :default_solr_params, or as defaults
    # on the solr side in the request handler itself. Request handler defaults
    # sniffing requires solr requests to be made with "echoParams=all", for
    # app code to actually have it echo'd back to see it.  
    #
    # :show may be set to false if you don't want the facet to be drawn in the 
    # facet bar
    config.add_facet_field 'author_name_ssim', :label => 'Forfatter', :single => true, :limit => 10, :collapse => false
    config.add_facet_field 'perioid_ssi', :label => 'Periode', :single => true, :limit => 10, :collapse => false, helper_method: :get_period_name


    # config.add_facet_field 'example_pivot_field', :label => 'Pivot Field', :pivot => ['format', 'language_facet']
    #
    # config.add_facet_field 'example_query_facet_field', :label => 'Publish Date', :query => {
    #    :years_5 => { :label => 'within 5 Years', :fq => "pub_date:[#{Time.now.year - 5 } TO *]" },
    #    :years_10 => { :label => 'within 10 Years', :fq => "pub_date:[#{Time.now.year - 10 } TO *]" },
    #    :years_25 => { :label => 'within 25 Years', :fq => "pub_date:[#{Time.now.year - 25 } TO *]" }
    # }

    # Have BL send all facet field names to Solr, which has been the default
    # previously. Simply remove these lines if you'd rather use Solr request
    # handler defaults, or have no facets.
    config.add_facet_fields_to_solr_request!

    # solr fields to be displayed in the index (search results) view
    #   The ordering of the field names is the order of the display 
    config.add_index_field 'author_id_ssi', :label => 'Forfatter', helper_method: :author_link, short_form: true, itemprop: :author
    ## if we have no author_id_ssi (link to author portrait, just show the author name)
    config.add_index_field 'author_name_tesim', :label => 'Forfatter',  short_form: true, itemprop: :author, unless: proc {|_context, _field_config, doc| doc['author_id_ssi'].present?}
    config.add_index_field 'volume_title_tesim', :label => 'Anvendt udgave', helper_method: :show_volume, short_form: true, itemprop: :isPartOf, unless: proc { |_context, _field_config, doc | doc.id == doc['volume_id_ssi'] }
    #config.add_index_field 'place_published_tesim', :label => 'Udgivelsessted', short_form: true
    #config.add_index_field 'date_published_ssi', :label => 'Udgivelsesdato', short_form: true
    config.add_index_field 'editor_ssi', :label => 'Redaktør', itemprop: :editor

    # solr fields to be displayed in the show (single result) view
    #   The ordering of the field names is the order of the display 

    # Work show fields
    config.add_show_field 'author_id_ssi', :label => 'Forfatter', helper_method: :author_link, itemprop: :author
    config.add_show_field 'volume_title_tesim', :label => 'Anvendt udgave', helper_method: :show_volume, itemprop: :isPartOf, unless: proc { |_context, _field_config, doc | doc.id == doc['volume_id_ssi'] }
    config.add_show_field 'publisher_tesim', :label => 'Udgiver', if: proc { |_context, _field_config, doc | doc['cat_ssi'] == 'volume' }
    config.add_show_field 'place_published_tesim', :label => 'Udgivelsessted', if: proc { |_context, _field_config, doc | doc['cat_ssi'] == 'volume' }
    config.add_show_field 'date_published_ssi', :label => 'Udgivelsesdato', if: proc { |_context, _field_config, doc | doc['cat_ssi'] == 'volume' }

    add_show_tools_partial(:feedback, callback: :email_action, if: :render_feedback_action?)
    config.show.document_actions.email.if = :render_email_action?
    config.show.document_actions.citation.if = :render_citation_action?


    # Overwriting this method to enable pdf generation using WickedPDF
    # Unfortunately the additional_export_formats method was quite difficult
    # to use for this use case.
    def show
      @response, @document = fetch URI.unescape(params[:id])

      # if we are showing a volume, fetch list of all works in the volume
      if @document['cat_ssi'].starts_with? 'volume'
        (@work_resp, @work_docs) = search_results({}) do |builder|
          if respond_to? (:blacklight_config)
            builder = blacklight_config.search_builder_class.new([:default_solr_parameters,:part_of_volume_search],builder)
            builder = builder.with({volumeid: @document['volume_id_ssi']})
            builder
          end
        end
      end

      #if we are showing a period, fetch a list of authors
      if @document['cat_ssi'].starts_with? 'period'
        (@auth_resp, @auth_docs) = search_results({}) do |builder|
          if respond_to? (:blacklight_config)
            builder = blacklight_config.search_builder_class.new([:default_solr_parameters,:build_authors_in_period_search],builder)
            builder = builder.with({perioid: @document['id']})
            builder
          end
        end
      end

      respond_to do |format|
        format.html { setup_next_and_previous_documents }
        format.json { render json: { response: { document: @document } } }
        format.pdf { send_pdf(@document, 'text') }
        format.xml do
          if @document['cat_ssi'] == 'volume'
            data = FileServer.get_file("/texts/#{@document['volume_id_ssi']}.xml")
            send_data data, type: 'application/xml'
          end
        end
        additional_export_formats(@document, format)
      end
    end

    def facsimile
      @response, @document = fetch URI.unescape(params[:id])
      respond_to do |format|
        format.html { setup_next_and_previous_documents }
        format.pdf { send_pdf(@document, 'image') }
      end
    end


    def periods
      (@response, @document_list) = search_results(params) do |builder|
        search_builder_class.new([:default_solr_parameters,:build_all_periods_search],builder)
      end
      render "index"
    end

    def authors
      (@response, @document_list) = search_results(params) do |builder|
        search_builder_class.new([:default_solr_parameters,:build_all_authors_search],builder)
      end
      render "index"
    end

    def allworks
      (@response, @document_list) = search_results(params)
      render "index"
    end

    # common method for rendering pdfs based on wicked_pdf
    # cache files in the public folder based on their id
    # perhaps using the Solr document modified field
    def send_pdf(document, type)
      name = document['work_title_tesim'].first.strip rescue document.id
      path = Rails.root.join('public', 'pdfs', "#{document.id.gsub('/', '_')}_#{type}.pdf")
      solr_timestamp = Time.parse(document['timestamp'])
      file_mtime = File.mtime(path) if File.exist? path.to_s
      # display the cached pdf if solr doc timestamp is older than the file's modified date
      if File.exist? path.to_s and ((type == 'text' and solr_timestamp < file_mtime) or type == 'image')
        send_file path.to_s, type: 'application/pdf', disposition: :inline, filename: name+".pdf"
      else
        render pdf: name,
               footer: {right: '[page] af [topage] sider'},
               save_to_file: path,
               header: {html: {template: 'shared/pdf_header.pdf.erb'},
                        spacing: 5},
               margin: {top: 15, # default 10 (mm)
                        bottom: 15},
               encoding: 'utf8', # needed here to encode danish characters
               # cover:  Rails.root.join('app', 'views', 'shared', 'pdf_cover.html')
               # Cover page can only be a static page OR

app/views/catalog/_feedback_form.html.erb
<%= form_tag url_for(:controller => controller_name, :action => "email"), :id => 'feedback_form', :class => "form-horizontal ajax_form", :method => :post do %>

  <div class="modal-body">
    <%= render :partial=>'/flash_msg' %>
    <div class="form-group">
      <div class="col-sm-10" style="display: none;">
        <%= email_field_tag :to, Rails.application.config_for(:adl)["feedback_mail"], class: 'form-control' %>
      </div>
    </div>

    <div class="form-group">
      <label class="control-label col-sm-2" for="message">
        <%= t('blacklight.email.form.work_title') %>
      </label>
      <div class="col-sm-10" >
        <%= text_field_tag :title, @document['work_title_tesim'].first.strip, class: 'form-control', disabled: "disabled" %>
      </div>
    </div>


    <div class="form-group">
      <label class="control-label col-sm-2" for="message">
        <%= t('blacklight.email.form.author') %>
      </label>
      <div class="col-sm-10" >
        <%= text_field_tag :title, @document['author_name_ssim'].first.strip, class: 'form-control', disabled: "disabled" %>
      </div>
    </div>

    <div class="form-group">
      <label class="control-label col-sm-2" for="message">
        <%= t('blacklight.email.form.volume_title') %>
      </label>
      <div class="col-sm-10" >
        <%= text_field_tag :title, @document['volume_title_tesim'].first.strip, class: 'form-control', disabled: "disabled" %>
      </div>
    </div>

    <div class="form-group">
      <label class="control-label col-sm-2" for="message">
        <%= t('blacklight.email.form.wrong_words') %>
      </label>
      <div class="col-sm-10">
        <%= text_area_tag 'message', params[:message], rows: 10, class: 'form-control'%>
      </div>
    </div>

    <%= hidden_field_tag "report", @report %>


  </div>
  <div class="modal-footer">
  <button type="submit" class="btn btn-primary"> <%= t('blacklight.sms.form.submit') %></button>
  </div>
<% end %>

app/views/catalog/_index_default.html.erb
<%# default partial to display solr document fields in catalog index view -%>
<% doc_presenter = index_presenter(document) %>
<% has_text  = document['has_text_ssi'].present? && document['has_text_ssi'] == 'yes' %>
<% has_facs  = document['has_facs_ssi'].present? && document['has_facs_ssi'] == 'yes' %>
<div class="x">
<dl class="document-metadata dl-horizontal dl-invert">
  <% collapse_id = "collapse-"+document['id'].gsub("#", "") %>
  <% result_id = "result-"+document['id'].gsub("#", "") %>
  <% text_label_id = "text-label-"+document['id'].gsub("#", "") %>

  <% collapse_fields = [] %>
  <% index_fields(document).each do |field_name, field| -%>
      <% if should_render_index_field? document, field %>
          <% label = render_index_field_label document, field: field_name %>
          <% value = doc_presenter.field_value field_name %>
          <% if value.present? and field.short_form %>
              <dt class="blacklight-<%= field_name.parameterize %>"><%= label %></dt>
              <dd class="blacklight-<%= field_name.parameterize %>"><%= value %></dd>
          <% elsif value.present?  %>
              <% collapse_fields << [label, value, field_name] %>
          <% end %>
      <% end -%>
  <% end -%>

  <!-- Show the 'I teskt' label, only if the search_field is fritekst-->
  <% if search_field_fritekst? %>
    <dt id=<%= text_label_id %>><%= t('blacklight.search.index.in_text') %></dt>
    <dd class="search-results" id =<%= result_id %> ></dd>
  <% end %>

  <dt><%= t('blacklight.search.index.format') %></dt>
  <dd>
    <% if has_text %>
            <%= bootstrap_glyphicon 'align-left' %>
            <span class="dlTxt"><%= t('blacklight.search.index.text') %></span>
    <% end %>
    <% if has_facs %>
            <%= bootstrap_glyphicon 'book' %>
            <span class="dlFaks"><%= t('blacklight.search.index.facsimile') %></span>
    <% end %>
  </dd>


  <div class="long_form_collapse collapse" id=<%= collapse_id %>>
    <% collapse_fields.each do |label, value, field_name| %>
          <dt class="blacklight-<%= field_name.parameterize %>"><%= label %></dt>
          <dd class="blacklight-<%= field_name.parameterize %>"><%= value %></dd>
    <% end %>
  </div>
  <% unless collapse_fields.empty? %>
      <a class="collapse-button" role="button" data-toggle="collapse" href="#<%= collapse_id %>" aria-expanded="false" aria-controls="<%= collapse_id %>" onclick="changeButtonLabel(this);">
        <%= t('blacklight.search.index.show_more') %>
      </a>
  <% end %>

</dl>

  <!-- Modal Table of content  -->
  <div class="modal fade" id="matches-<%= document['id'] %>" tabindex="-1" role="dialog" aria-labelledby="textMatches">
    <div class="modal-dialog" role="document">
      <div class="modal-content">
        <div class="modal-header">
          <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
          <h4 class="modal-title" id="textMatches">
            Alle forekomster
          </h4>
        </div>
        <div class="modal-body" id="matchesModalBody-<%= document['id']%>">

        </div>
        <div class="modal-footer">
          <button type="button" class="btn btn-default" data-dismiss="modal">Luk</button>
        </div>
      </div>
    </div>
  </div>

</div>

<%= javascript_tag do %>
    <% if search_field_fritekst? %>
      $(document).ready(
              function () {
                  index_work_search("<%= document['id'] %>", $('#<%= result_id %>'), $('#<%= text_label_id %>'));
              });
    <% end %>
<% end %>

app/views/catalog/_index_header_author.html.erb
<%# header bar for doc items in index view -%>
<div class="documentHeader row">
  <%# main title container for doc partial view
      How many bootstrap columns need to be reserved
      for bookmarks control depends on size.
  -%>
  <% document_actions = capture do %>
      <% # bookmark functions for items/docs -%>
      <%= render_index_doc_actions document, wrapping_class: "index-document-functions col-sm-3 col-lg-2" %>
  <% end %>

  <h4 class="index_title document-title-heading <%= document_actions.present? ? "col-sm-9 col-lg-10" : "col-md-12" %>">
    <a href="<%= solr_document_url(document.id) %>">
      <span class="author-img-thumbnail">
        <%= image_tag "authors/#{document.id}.jpg" %>
      </span>
    </a>
    <%= link_to_document document %>
  </h4>

</div>

app/views/catalog/_index_header_default.html.erb
<%# header bar for doc items in index view -%>
<div class="documentHeader row">
  <%# main title container for doc partial view
      How many bootstrap columns need to be reserved
      for bookmarks control depends on size.
  -%>
  <% document_actions = capture do %>
    <% # bookmark functions for items/docs -%>
    <%= render_index_doc_actions document, wrapping_class: "index-document-functions col-sm-3 col-lg-2" %>
  <% end %>

  <h4 class="index_title document-title-heading <%= document_actions.present? ? "col-sm-9 col-lg-10" : "col-md-12" %>">
    <% if counter = document_counter_with_offset(document_counter) %>
      <!--span class=" ">
        <%= t('blacklight.search.documents.counter', counter: counter) %>
      </span-->
    <% end %>
    <a href="<%= solr_document_url(document.id) %>">
      <span class="glyphicon glyphicon-book"></span>
    </a>
      <%= link_to_document document %>
  </h4>

  <%= document_actions %>
</div>

app/views/catalog/_index_header_period.html.erb
<%# header bar for doc items in index view -%>
<div class="documentHeader row">
  <%# main title container for doc partial view
      How many bootstrap columns need to be reserved
      for bookmarks control depends on size.
  -%>
  <% document_actions = capture do %>
    <% # bookmark functions for items/docs -%>
    <%= render_index_doc_actions document, wrapping_class: "index-document-functions col-sm-3 col-lg-2" %>
  <% end %>

  <h4 class="index_title document-title-heading <%= document_actions.present? ? "col-sm-9 col-lg-10" : "col-md-12" %>">
    <% if counter = document_counter_with_offset(document_counter) %>
      <!--span class=" ">
        <%= t('blacklight.search.documents.counter', counter: counter) %>
      </span-->
    <% end %>
    <a href="<%= solr_document_url(document.id) %>">
      <span class="glyphicon glyphicon-time"></span>
    </a>
    <%= link_to_document document %>

  </h4>
</div>

app/views/catalog/_index_period_default.html.erb
<%# header bar for doc items in index view -%>
<div class="documentHeader row">
  <%# main title container for doc partial view
      How many bootstrap columns need to be reserved
      for bookmarks control depends on size.
  -%>
  <% document_actions = capture do %>
    <% # bookmark functions for items/docs -%>
    <%= render_index_doc_actions document, wrapping_class: "index-document-functions col-sm-3 col-lg-2" %>
  <% end %>

  <h4 class="index_title document-title-heading <%= document_actions.present? ? "col-sm-9 col-lg-10" : "col-md-12" %>">
    <% if counter = document_counter_with_offset(document_counter) %>
      <!--span class=" ">
        <%= t('blacklight.search.documents.counter', counter: counter) %>
      </span-->
    <% end %>
    <a href="<%= solr_document_url(document.id) %>">
      <span class="glyphicon glyphicon-book"></span>
    </a>
    <%= link_to_document document %>
  </h4>

  <%= document_actions %>
</div>

app/views/catalog/_search_form.html.erb
<div class="search-not-main box-gradient-blue fixed-top-second">
  <div class="container search-bg">
    <%= form_tag search_action_url, :method => :get, :class => 'search ' do %>
        <div class="input-group input-group-lg search-form-with-tooltips">
          <% unless search_fields.empty? %>
              <label for="search_field" class="sr-only">
                <%= t('blacklight.search.form.search_field.label') %>
              </label>
              <span class="sr-only">
                       <%= t('blacklight.search.form.search_field.post_label') %>
                </span>
          <% end %>
          <span class="input-group-btn hidden-xs">
              <%= select_tag(:search_field, options_for_select(search_fields, h(params[:search_field])), :title => t('blacklight.search.form.search_field.title'), :class => "input-lg") %>
            </span>
          <label for="q" class="sr-only"><%= t('blacklight.search.form.search.label') %></label>
          <%= text_field_tag :q, params[:q], :placeholder => t('blacklight.search.form.search.placeholder'), :class => "search_q q form-control", :id => "q", :autofocus => should_autofocus_on_search_box? %>
          <span class="input-group-btn ">
                <button type="submit" class="btn btn-primary btn-lg" id="search">
                  <span class="submit-search-text"><%= t('blacklight.search.form.submit') %></span>
                  <span class="glyphicon glyphicon-search"></span>
                </button>
            </span>
<span class="input-group-btn">
          <span class="search-tooltip ">?
            <span class="tooltiptext">
                <div class="panel panel-default">
  <div class="panel-heading">Søgetips</div>
  <div class="panel-body">
    <ul class="advanced-help">

     <li>Kombiner søgertermer for at finde
     </li>

     <li>Brug " for at søge efter en sætning

     </li><li>Brug "+" før et ord hvis resultatet skal indeholde dette ord.</li>

     <li>Brug "-" for at udelukke ord fra søgningen.

     </li><li>Brug "OR", "AND", and "NOT" til mere avancerede søgninger. </li>
     <li>Bemærk at systemet understøtter ikke wildcards. Trunkering udføres automatisk af systemet</li>
   </ul>
  </div>
</div>
              </span>
          </span>
</span>
        </div>

    <% end %>
  </div>
</div>

app/views/catalog/_search_header.html.erb
<% unless ['authors','periods'].include? controller.action_name %>
<div class="documents">
   <%= render 'sort_and_per_page' %>
   <%= render 'did_you_mean' %>
   <%= render 'constraints' %>
</div>
<% end %>

app/views/catalog/_show_author.html.erb
<%# default partial to display solr document fields in catalog show view -%>
<% doc_presenter = show_presenter(document) %>
<div class="text-content">

  <div class="period-writers-list text-left">
     <a class="icon-list" href="<%= "/?utf8=✓&search_field=author&q=#{document['work_title_tesim'].try(:join)}" %>">
      <span class="glyphicon glyphicon-list"></span> Værkliste i ADL
     </a>

    <a class="icon-list" href="<%= solr_document_path(document.id, format:'pdf')%>" target="_blank">
      <span class="glyphicon glyphicon-save"></span> Download forfatterportræt (PDF)
    </a>
  </div>

<div class="row divider-space">
  <div class="col-md-1"></div>
  <div class="col-md-10">
    <div class="divider clearfix">
      <div class="left"></div>
      <div class="midt"></div>
      <div class="right"></div>
    </div>
  </div>
  <div class="col-md-1"></div>
</div>

    <div class="text">
      <% unless doc_presenter.field_value("author_name_tesim").empty? %>
        <div class="dl-horizontal  dl-invert pull-left">
          <strong><span class="blacklight-author_name_tesim text-left-important"><%= t('author.author_potrait_written_by') %> </span></strong>
          <span class="blacklight-author_name_tesim">&nbsp;<%= doc_presenter.field_value "author_name_tesim" %></span>
        </div>
      <% end %>

        <div class="pull-right thumbnail">
          <%= image_tag "authors/#{document.id}.jpg" %>
        </div>
        <div><br/><br/><br/></div>
        <% text ||= FileServer.render_snippet(document.id,{c: 'authors'}) %>
        <%= text.html_safe %>
      </div>
    </div>

app/views/catalog/_show_header_volume.html.erb
<% document ||= @document %>
<% doc_presenter = show_presenter(document) %>
<% # bookmark/folder functions -%>

<div class="page-header">
  <div class="container search-bg">
    <h2><span class="glyphicon glyphicon-book"></span> <%= document['work_title_tesim'].first %></h2>
  </div>
</div>

<div class="workHeaderFixContainer">
  <div class="row">
      <div class="workHeader">
        <dl class="dl-horizontal  dl-invert">
          <% document_show_fields(document).each do |field_name, field| -%>
              <% if should_render_show_field? document, field %>
                  <dt class="blacklight-<%= field_name.parameterize %>"><%= render_document_show_field_label document, field: field_name %></dt>
                  <dd class="blacklight-<%= field_name.parameterize %>"><%= doc_presenter.field_value field_name %></dd>
              <% end -%>
          <% end -%>
        </dl>
        <div class="hidden"><%= link_to "Hent TEI", solr_document_path(@document['volume_id_ssi'], :format => 'xml') %></div>
      </div>
  </div>
</div>

app/views/catalog/_show_period.html.erb
<%# default partial to display solr document fields in catalog show view -%>
<% doc_presenter = show_presenter(document) %>

    <div class="text-content">
      <div class="text">

      <div class="period-writers-list">

        <dl>
          <dt class="blacklight-author_name_tesim">Forfattere i ADL</dt>
        </dl>

        <ul>
        <% @auth_docs.each do |doc| %>
            <li><%= link_to doc['work_title_tesim'].join, solr_document_path(doc['id']) %></li>
        <% end %>
        </ul>

      </div>

      <div class="row divider-space">
        <div class="col-md-1"></div>
        <div class="col-md-10">
          <div class="divider clearfix">
            <div class="left"></div>
            <div class="midt"></div>
            <div class="right"></div>
          </div>
        </div>
        <div class="col-md-1"></div>
      </div>

        <dl class="dl-horizontal  dl-invert pull-left">
          <dt class="blacklight-author_name_tesim">Periodebeskrivelse af</dt>
          <dd class="blacklight-author_name_tesim"><%= doc_presenter.field_value "author_name_tesim" %></dd>
        </dl>
        <div class="pull-right text-right">
          <a target="_blank" href="">
            <span class="glyphicon glyphicon-save"></span> <%= link_to "Tekst", solr_document_path(document.id, format: 'pdf') %>
          </a>
        </div>

        <div><br/></div>

        <% text ||= FileServer.render_snippet(document.id,{c: 'periods'}) %>
        <%= text.html_safe %>
      </div>
    </div>

app/views/catalog/_show_volume.html.erb
<% document ||= @document %>

<div class="row divider-space">
  <div class="col-md-1"></div>
  <div class="col-md-10">
    <div class="divider clearfix">
      <div class="left"></div>
      <div class="midt"></div>
      <div class="right"></div>
    </div>
  </div>
  <div class="col-md-1"></div>
</div>


<div class="row content-body">
<div class="container">
  <h2><%= t('views.volume.content')%></h2>

  <dl>


<% @work_docs.each do |doc| %>
   <dd><%= link_to doc['work_title_tesim'].join, solr_document_path(doc['id']) unless doc['work_title_tesim'].blank?  %></dd>
<% end %>
</dl>
</div>
</div>

app/views/catalog/_show_work.html.erb
<%= render :partial => 'show_text_and_facs', locals: { document: @document}%>

app/views/catalog/_simple_search_form.html.erb
<%= form_tag search_action_url, :method => :get, :class => '' do %>
    <%= render_hash_as_hidden_fields(search_state.params_for_search.except(:q, :search_field, :qt, :page, :utf8)) %>
    <%= hidden_field_tag :search_field, "Alt" %>

    <div class="input-group input-group-lg search-form-with-tooltips">
      <label for="q" class="sr-only"><%= t('blacklight.search.form.search.label') %></label>
      <%= text_field_tag :q, params[:q], :placeholder => t('blacklight.search.form.search.placeholder'), :class => "search_q q form-control", :id => "q", :autofocus => should_autofocus_on_search_box? %>

      <span class="input-group-btn ">
                <button type="submit" class="btn btn-primary btn-lg" id="search">
                  <span class="submit-search-text"><%= t('blacklight.search.form.submit') %></span>
                  <span class="glyphicon glyphicon-search"></span>
                </button>
      </span>

      <span class="input-group-btn">
        <span class="search-tooltip ">?
         <span class="tooltiptext">
            <div class="panel panel-default">
              <div class="panel-heading">Søgetips</div>
              <div class="panel-body">
                <ul class="advanced-help">
                  <li>Du kan bruge "OR", "AND" og "NOT" til kombinerede søgninger. </li>
                  <li>Bemærk at systemet ikke understøtter wildcards. Trunkering udføres automatisk af systemet.</li>
                  <li>Hvis du søger på flere ord, kan du sætte "+" før et ord hvis resultatet <i>skal</i> indeholde dette ord, og "-" foran et ord hvis resultatet ikke må indeholde det pågældende ord.</li>
                </ul>
              </div>
            </div>
         </span>
        </span>
      </span>

    </div>

<% end %>